### ISSUE TITLE
Compatible with Laravel 8.0

### ISSUE THREAD

**Issue by massimodellarovere** [Rackbeat/laravel-ui-avatars#10]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rackbeat/laravel-ui-avatars ^0.8.5 -> satisfiable by rackbeat/laravel-ui-avatars[0.8.5].

**Comment by mbardelmeijer** [comment]
👍

**Comment by LasseRafn** [comment]
Thank you!😄

**Comment by LasseRafn** [comment]
I will make a change shortly
