### ISSUE TITLE
Incompatible with Laravel 10

### ISSUE THREAD

**Issue by tomatoTom** [Rackbeat/laravel-ui-avatars#14]
- PHP 8.2
- Laravel 10.0

I tried to install it via composer: `rackbeat/laravel-ui-avatars`

Response:
`rackbeat/laravel-ui-avatars[dev-master, 1.1] require illuminate/support ^7.0|^8.0|^9.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires rackbeat/laravel-ui-avatars * -> satisfiable by rackbeat/laravel-ui-avatars[dev-master, 0.5, ..., 0.9, 1.0, 1.1, 9999999-dev].`

**Comment by dualznz** [comment]
yup i too have this issue

**Comment by LasseRafn** [comment]
Hi! its out now 👍🏻  version 1.2

https://github.com/Rackbeat/laravel-ui-avatars/releases/tag/1.2
