### ISSUE TITLE
Package not support laravel/framework v5.8.8 

### ISSUE THREAD

**Issue by NikoNar** [Rackbeat/laravel-ui-avatars#3]
Problem 1
    - Installation request for rackbeat/laravel-ui-avatars ^0.6.0 -> satisfiable by rackbeat/laravel-ui-avatars[0.6].
    - Conclusion: remove laravel/framework v5.8.8
    - Conclusion: don't install laravel/framework v5.8.8
    - rackbeat/laravel-ui-avatars 0.6 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.8].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.8].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.8].
    - Installation request for laravel/framework (locked at v5.8.8, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.8].

**Comment by LasseRafn** [comment]
Fixed! Sorry
