### ISSUE TITLE
[BUG] Urlencoding the whole url does not produce a valid url.

### ISSUE THREAD

**Issue by karlerss** [Rackbeat/laravel-ui-avatars#6]
Hello!

https://github.com/Rackbeat/laravel-ui-avatars/blob/master/src/Generators/ApiGenerator.php#L102

This does not produce valid urls.

**Comment by LasseRafn** [comment]
Hi! Thanks for this. Actually it is just terrible naming, I'm sorry!

Its only really used in Gravatar urls, and shouldn't really be used elsewhere. I'll change naming
