### ISSUE TITLE
Is there a way to use 2 namefields? (e.g. firstname, lastname)

### ISSUE THREAD

**Issue by c4sti3l** [Rackbeat/laravel-ui-avatars#8]
My user has to "namefields" and I want to display the first char from each of them.

**Comment by LasseRafn** [comment]
Yes! If you make a method on the user class like so:

```php
	protected function getAvatarName() {
		return $this->name_one . ' ' . $this->name_two;
	}
```

It should use both names. (replace `name_one` and `name_two` with the actual fields)
